export const ADD_GENRE = 'ADD_GENRES';
export const UPDATE_OFFSET = 'UPDATE_OFFSET';
export const UPDATE_GAMES_LOADING = 'UPDATE_GAMES_LOADING';
export const UPDATE_RATING = 'UPDATE_RATING';
export const UPDATE_SEARCH_TOGGLE = 'UPDATE_SEARCH_TOGGLE';
export const UPDATE_AFTER_DATE = 'UPDATE_AFTER_DATE';
export const UPDATE_GENRE_LIST = 'UPDATE_GENRE_LIST';
export const UPDATE_GAME_LIST = 'UPDATE_GAME_LIST';